name: Publish Docker image

on:
  push:
    branches:
      - main

jobs: 
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        run: echo "Abrahm"
      
