name: Publish Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: https://hub.docker.com/
  IMAGE_NAME: ${{ github.repository }}

jobs: 
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        env:
          MY_SECRET_KEY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: echo $REGISTRY && echo $IMAGE_NAME
      
